name: Barnett Farm
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000800'
    - '#004500'
    - '#2f6c5e'
    - '#5ea81c'
    - '#eee9ec'
  brandStrength: 0.4375
  lightness: 0.9741361439228058
  saturation: 0
  rhythmicContrast: 0.9716169442981482
purpose: []
